### ISSUE TITLE
No menu for those who have level 500 and above

### ISSUE THREAD

**Issue by Mateyoo** [pajbot/pajbot#2108]
I set up pajbot on a spare VPS for a streamer friend of mine, and we both want to have access to the admin zone.
I made a friend level 500, and he doesn't have a menu at all.

My (admin) screenshot of the inspect element tab:
https://i.imgur.com/NDyHnYa.png
The friend's screenshot with level 500 of the inspect element tab:
https://i.imgur.com/lU7Mdpv.png
(I also tried giving him Super Moderator, and it didn't fix it.)

Any ideas?

**Comment by Mateyoo** [comment]
Fixed:
Solution was to log out of twitch, and then log back in.
Suddenly the Admin Zone button appeared, and the menu too.

**Comment by RAnders00** [comment]
Yes, this happens because user details including level are fetched only on login: https://github.com/pajbot/pajbot/blob/9ed61de2b205f79a516c4682a539ff6cec120dad/pajbot/web/routes/base/login.py#L139

They are then stored on the browser in a cryptographically signed cookie.

It‘s interesting that you bring this up, because it‘s technically possible for a user to still have admin panel access even after demoting them below level 500 because of this.

**Comment by RAnders00** [comment]
Nevermind. I spoke too soon on that. Endpoints decorated with `@requires_level(…)` do check the level with the DB every single time. https://github.com/pajbot/pajbot/blob/9ed61de2b205f79a516c4682a539ff6cec120dad/pajbot/web/utils.py#L38-L44

**Comment by RAnders00** [comment]
It turns out the admin login link is based on the level stored in the session though: https://github.com/pajbot/pajbot/blob/9ed61de2b205f79a516c4682a539ff6cec120dad/templates/layout.html#L80-L82

**Comment by RAnders00** [comment]
I think this issue is extremely minor, so I‘ve closed it again. Feel free to reopen if anyone disagrees with that
